In [1]:
from LABNET import Neuron, Net

In [2]:
dl_big = [
    ['i']
    ,['i']
    ,['i']
    ,['i']
    ,['i']
    ,['i']
    ,['i']
    ,['i'] #0-7 for inputs
    
    ,['fc',[0,1,2]]
    ,['fc',[-2,3,-4]]
    ,['fc',[3,4,5]]
    ,['fc',[3,5,7]]
    ,['fc',[0,7]] #8 - 12 for this layer
    
    ,['fc',[8,10]]
    ,['fc',[9,-11]]
    ,['fc',[12]]
    ,['fc',[-8,-9]] #13 - 16
    
    
    
    ,['o',[-13,14]]
    ,['o',[-14,15,-16]]
    ,['o',[-15,-16]]
    ,['o',[-13,16]]
    
]

In [5]:
nn_big = Net(dl_big)
nn_big.generate_inputs()
nn_big.generate_outputs()
nn_big.tensorize()

self.inputs and self.outputs are now tensors of shape torch.Size([256, 8]) and torch.Size([256, 4]) respectively!


In [6]:
nn_big.outputs

tensor([[False,  True, False, False],
        [False, False,  True, False],
        [False,  True, False, False],
        ...,
        [False, False, False,  True],
        [False, False, False,  True],
        [False, False, False,  True]])

In [8]:
nn_big.percent_true()

[tensor(0.0938), tensor(0.0781), tensor(0.1562), tensor(0.7500)]

In [9]:
nn_big.input_size

8

In [10]:
import torch
import torch.nn as nn
import torch.optim as optim

In [25]:
# Define the model
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.hidden_1 = nn.Linear(nn_big.input_size, 5) ##make these all variables duh
        self.hidden_2 = nn.Linear(5,4)
        self.output = nn.Linear(4, nn_big.output_size)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.hidden_1(x))
        x = self.relu(self.hidden_2(x))
        x = self.output(x)
        return x

In [26]:
model = MyModel()

In [27]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [28]:
input_data = nn_big.inputs.float()
output_data = nn_big.outputs.float()

In [29]:
input_data.dtype

torch.float32

In [30]:
dir(model)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_backward_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_ver

In [32]:
# Training loop
num_epochs = 5
for epoch in range(num_epochs):
    # Forward pass
    output = model(input_data)

    # Compute the loss
    loss = criterion(output, output_data)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    loss.item()

    
    print(model.hidden_1.weight)
    print(model.hidden_2.weight)
    print(model.output.weight)

# After training, you can use the model to make predictions
test_input = torch.randn(1, 8)  # Single test input with 8 values
predicted_output = model(test_input)
print("Predicted output:", predicted_output)

Parameter containing:
tensor([[-4.5754e-02, -1.2435e-01,  3.4553e-01, -6.3660e-02, -1.5300e-01,
         -2.9018e-01,  1.9608e-01, -1.2444e-02],
        [ 1.3079e-01,  7.5161e-02, -1.1929e-01,  1.1127e-01, -2.7228e-01,
         -3.1584e-04,  2.3139e-01, -2.3540e-01],
        [-2.7023e-01, -3.3425e-01,  3.5149e-02, -1.2247e-01, -3.2816e-01,
         -3.1998e-01,  9.0744e-02, -3.1496e-01],
        [-1.7439e-01, -1.4985e-02, -7.8979e-03,  2.1194e-01, -7.3855e-02,
          2.9550e-01, -1.1059e-01, -1.9230e-01],
        [ 1.6225e-02,  2.5856e-01, -1.1404e-01, -2.3967e-01, -9.9704e-02,
         -1.9040e-01, -1.0715e-01,  3.1491e-01]], requires_grad=True)
Parameter containing:
tensor([[-0.1751,  0.0116, -0.3994,  0.3107, -0.3202],
        [ 0.1451, -0.1175, -0.0502, -0.1459, -0.2935],
        [ 0.3266,  0.2314, -0.1971, -0.0954, -0.0626],
        [-0.3727, -0.2520, -0.2729,  0.2970, -0.1119]], requires_grad=True)
Parameter containing:
tensor([[ 0.4874,  0.1602, -0.2628, -0.2831],
        [-0