In [1]:
import torch

In [2]:
x = torch.tensor([[1,2,3,4],[5,5,2,2],[6,1,2,1],[3,1,5,1]])

In [4]:
x.shape

torch.Size([4, 4])

In [5]:
permutation = torch.randperm(4)

# Shuffle the rows of the tensor using the permutation indices
shuffled_tensor = x[permutation]

In [6]:
shuffled_tensor

tensor([[1, 2, 3, 4],
        [6, 1, 2, 1],
        [5, 5, 2, 2],
        [3, 1, 5, 1]])

In [7]:
x

tensor([[1, 2, 3, 4],
        [5, 5, 2, 2],
        [6, 1, 2, 1],
        [3, 1, 5, 1]])

In [14]:
def reorder_rows(target_tensor, candidate_tensor):
    # Convert tensors to float type
    target_tensor = target_tensor.float()
    candidate_tensor = candidate_tensor.float()

    # Calculate pairwise distances between rows
    distances = torch.cdist(candidate_tensor.unsqueeze(1), target_tensor.unsqueeze(0))
    
    # Calculate the sum of distances for each row
    row_sums = torch.sum(distances, dim=2)

    # Sort the rows based on the sum of distances
    _, indices = torch.sort(row_sums)

    # Reorder the rows in the candidate tensor
    reordered_tensor = candidate_tensor[indices]

    return reordered_tensor

In [15]:
reorder_rows(x,shuffled_tensor)

tensor([[[1., 2., 3., 4.]],

        [[1., 2., 3., 4.]],

        [[1., 2., 3., 4.]],

        [[1., 2., 3., 4.]]])

In [24]:
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances, cosine_distances

def compare_rows(tensor_a, tensor_b, dist='euclidean'):
    if tensor_a.shape != tensor_b.shape:
        raise ValueError("Input tensors must have the same shape.")
    if dist == 'euclidean':
        distances = euclidean_distances(tensor_a, tensor_b)
    elif dist == 'cosine':
        distances = cosine_distances(tensor_a, tensor_b)
    else:
        raise ValueError("Invalid distance metric. Please choose either 'euclidean' or 'cosine'.")

    min_sum = np.sum(np.min(distances, axis=1))
    return distances,min_sum

# Example usage
tensor_a = np.array([[1, 2, 3], [4, 5, 6]])
tensor_b = np.array([[7, 8, 9], [10, 11, 12]])

distances,m = compare_rows(tensor_a, tensor_b, dist='euclidean')
print(distances,m)

ValueError: Input tensors must have the same shape.

In [21]:
distances = compare_rows(x, shuffled_tensor, dist='euclidean')
print(distances)

(array([[0.        , 6.        , 5.47722558, 4.24264069],
       [5.47722558, 4.24264069, 0.        , 5.47722558],
       [6.        , 0.        , 4.24264069, 4.24264069],
       [4.24264069, 4.24264069, 5.47722558, 0.        ]]), 0.0)
